# Generated by Django 5.2.6 on 2025-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pessoas', models.PositiveIntegerField()),
                ('anota', models.TextField()),
            ],
        ),
    ]
